### ISSUE TITLE
STS Register Hex Values confusing

### ISSUE THREAD

**Issue by vyeevani** [matthieuvigne/STS_servos#6]
The values of the hex memory addresses in the excel are wrong right now. would be good to just get rid of that column entirely leaving only unambiguous decimal values

**Comment by matthieuvigne** [comment]
I'm not sure to understand which document you are referring to. Are you talking about Column D in Sheet 1 of STS3215 Memory Table.xlsx ? Because this column look correct to me - in fact, it is automatically generated from the decimal value by a formula. Which software are you using to open the file ? Maybe the formula computation messes things up ?

**Comment by vyeevani** [comment]
You're right. I was using numbers on macOS which seems to have messed up the computation.
